sonar.projectKey=init4saurabh_fe-to-deployment-lifecycle
sonar.organization=init4saurabh

sonar.sources=apps,packages

sonar.tests=apps

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=apps/react-app/coverage/lcov.info

sonar.exclusions=\
**/coverage/**,\
**/dist/**,\
**/.github/**,\
packages/eslint-config/**,\
packages/typescript-config/**,\
packages/jest-config/**